[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | .eggs
  | build
)/
'''

[tool.check-manifest]
ignore = [
    'examples*',
    '.*',
    'pyproject.toml',
    'CODE_OF_CONDUCT.md',
]
